version: "3.7"
services:
  vault:
    image: hashicorp/vault:1.13.0
    container_name: vault
    hostname: vault
    ports:
      - 8200:8200
    volumes:
      - ./config.hcl:/vault/config/config.hcl
      - vault-data:/vault/file/
    environment:
      - VAULT_ADDR=http://localhost:8200
    cap_add:
      - IPC_LOCK
    command: server
    restart: always

  vault-init:
    image: hashicorp/vault:1.13.0
    container_name: vault-init
    environment:
      - VAULT_ADDR=http://vault:8200
      - MY_VAULT_TOKEN=${MY_VAULT_TOKEN:-test}
    volumes:
      - ./vault-root-token:/vault/file/vault-root-token
      - ./vault-init.sh:/usr/local/bin/vault-init.sh
      - ./vaultlogs:/vault/logs
      - vault-data:/vault/file/
    command: chmod +x /usr/local/bin/vault-init.sh
    restart: on-failure
    depends_on:
      - vault

volumes:
  vault-data:
